# Build-time emitter for lexical spelling-variant pairs that are derivable from corpus frequency
# data (as opposed to the hand-curated US/UK dialectal rules in +utils_rhyme.rb+). Output goes to
# +generated/spelling_variants_auto.txt+, which +load_variants_raw+ reads alongside the manual
# +spelling_variants.txt+. All corpus I/O stays here: the runtime +preferred_form+ path never
# consults +wordfreq.tsv+ or SUBTLEX directly.
#
# Currently covers the -oes/-os plural alternation on -o nouns (tomatoes/tomatos,
# aficionados/aficionadoes, mottos/mottoes, …). The winner is whichever spelling is ≥3× more
# frequent on the wordfreq Zipf scale; when the gap is narrower than that, or both forms are
# absent from wordfreq, the morphologically simpler -os spelling wins deterministically so the
# UI never displays both variants of a truly-tied pair.

require "set"
require_relative "utils_rhyme"

# log10(3.0) ≈ 0.477: a spelling with ≥3× the wordfreq density of its sibling wins; below that
# we declare the pair tied and fall back to the deterministic shorter-wins rule.
CORPUS_ZIPF_DECISIVE_DELTA = Math.log10(3.0)

SPELLING_VARIANTS_AUTO_HEADER = <<~HEADER
  # Auto-detected lexical spelling variant pairs.
  #
  # Generated by lib/rhymecrime/dict/corpus_variants.rb during dict-build; do NOT hand-edit.
  # Format matches lib/rhymecrime/dict/spelling_variants.txt: one line per pair, preferred form
  # first. Loaded at runtime by load_variants_raw in utils_rhyme.rb.
HEADER

# Emit +generated/spelling_variants_auto.txt+ from +word_dict+ and +wordfreq_hash+. Each pair
# listed appears on both sides of +word_dict+ with a shared pronunciation (stress-insensitive).
# Safe to call inside +build_word_dict+ before +strip_dispreferred_headwords_from_rdict!+ so the
# rime-dict bucket stripper sees the resolved pairs on the same build.
def emit_spelling_variants_auto!(word_dict, wordfreq_hash)
  previous_word_dict = $word_dict
  previous_variants = $variants
  $word_dict = word_dict
  pairs = o_plural_corpus_pairs(word_dict, wordfreq_hash)
  ensure_generated_dict_dir!
  path = generated_dict_path(SPELLING_VARIANTS_AUTO_FILENAME)
  File.open(path, "w", encoding: "UTF-8") do |f|
    f.print(SPELLING_VARIANTS_AUTO_HEADER)
    pairs.each { |preferred, alt| f.puts("#{preferred} #{alt}") }
  end
  puts "Wrote #{pairs.size} auto-detected spelling variants to #{path}"
  pairs
ensure
  $word_dict = previous_word_dict
  $variants = nil # force reload so downstream preferred_form sees the new pairs
  clear_spelling_variant_hyphen_caches!
  _ = previous_variants # referenced to silence unused-var lint; callers re-derive via variants()
end

# Scan +word_dict+ for -oes/-os plural pairs that both survive as headwords and share the
# same lemma (a stronger signal at build time than pronunciation overlap: dict-build's
# inflection pipeline assigns quirky secondary stress to alternate-form CMU entries, but
# only groups them under one base lemma when morphology actually recognizes the pair).
# Returns a sorted, deduped array of [preferred, alternate].
def o_plural_corpus_pairs(word_dict, wordfreq_hash)
  seen = Set.new
  pairs = []
  word_dict.each_key do |w|
    candidate = o_plural_candidate_pair(w)
    next unless candidate
    oes, os = candidate
    next if seen.include?(oes)
    oes_entry = word_dict[oes]
    os_entry = word_dict[os]
    next unless oes_entry && os_entry
    oes_lemma = oes_entry[2]
    os_lemma = os_entry[2]
    next unless oes_lemma && os_lemma && oes_lemma == os_lemma
    winner = pick_corpus_winner_by_zipf(oes, os, wordfreq_hash, deterministic_fallback: os)
    preferred, alt = (winner == oes) ? [oes, os] : [os, oes]
    pairs << [preferred, alt]
    seen << oes
    seen << os
  end
  pairs.sort
end

# Pick whichever spelling has the decisively higher wordfreq Zipf (delta ≥
# +CORPUS_ZIPF_DECISIVE_DELTA+); on a tie (or when both forms are absent from wordfreq) return
# +deterministic_fallback+. Callers pass the morphologically simpler -os form as the fallback so
# the UI never displays both spellings of a truly-tied pair.
def pick_corpus_winner_by_zipf(a, b, wordfreq_hash, deterministic_fallback:)
  za = (wordfreq_hash[a] || 0.0).to_f
  zb = (wordfreq_hash[b] || 0.0).to_f
  diff = za - zb
  return a if diff >= CORPUS_ZIPF_DECISIVE_DELTA
  return b if -diff >= CORPUS_ZIPF_DECISIVE_DELTA
  deterministic_fallback
end
